[package]
name = "saketo_rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
polyseed = { path = "../external_libs/monero-wallet-util/polyseed" }
monero-seed = { path = "../external_libs/monero-wallet-util/seed" }
rand = "0.8.5"
zeroize = "1.8.1"
